Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.network "forwarded_port", guest: 80, host: 8090
  config.vm.provision "shell",
    inline: "apt update && apt install -y nginx && service nginx start"
end
